/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import helpdesk.Cola;
import helpdesk.NodoColaTiquete;
import helpdesk.Tiquete;
import javax.swing.JOptionPane;

public class MenuUsuario extends javax.swing.JFrame {

    private Tiquete tiquete;
    private Cola laCola;

    public MenuUsuario(Cola laCola, Tiquete tiquete) {
        initComponents();

        this.tiquete = tiquete;
        this.laCola = laCola;

        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TituloPanelUSuario = new javax.swing.JTextField();
        Version = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        BotonCrearTiquete = new javax.swing.JButton();
        BotonMostrarTiquetes = new javax.swing.JButton();
        NuevoTiqueteTitulo = new javax.swing.JTextField();
        TiquetesActivosTitulo = new javax.swing.JTextField();
        IDEmpleado = new javax.swing.JLabel();
        TextFieldNumEmpleado = new javax.swing.JTextField();
        Nombre = new javax.swing.JLabel();
        TextFieldNombre = new javax.swing.JTextField();
        Descripcion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaDescripcion = new javax.swing.JTextArea();
        Telefono = new javax.swing.JLabel();
        TextFieldTelefono = new javax.swing.JTextField();
        Email = new javax.swing.JLabel();
        TextFieldEmail = new javax.swing.JTextField();
        IDEmpleadoHistorial = new javax.swing.JLabel();
        TextFieldIDEmpleHistorial = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TiquetesActivos = new javax.swing.JTextPane();
        BotonCerrar = new javax.swing.JButton();

        setTitle("Panel Usuario");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setToolTipText("");

        TituloPanelUSuario.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        TituloPanelUSuario.setForeground(new java.awt.Color(0, 51, 204));
        TituloPanelUSuario.setText("PANEL DE USUARIO");
        TituloPanelUSuario.setBorder(null);

        Version.setText("Version 1.01");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        BotonCrearTiquete.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        BotonCrearTiquete.setText("Crear");
        BotonCrearTiquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCrearTiqueteActionPerformed(evt);
            }
        });

        BotonMostrarTiquetes.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        BotonMostrarTiquetes.setText("Mostrar");
        BotonMostrarTiquetes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMostrarTiquetesActionPerformed(evt);
            }
        });

        NuevoTiqueteTitulo.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        NuevoTiqueteTitulo.setForeground(new java.awt.Color(0, 51, 204));
        NuevoTiqueteTitulo.setText("Nuevo Tiquete");
        NuevoTiqueteTitulo.setBorder(null);

        TiquetesActivosTitulo.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        TiquetesActivosTitulo.setForeground(new java.awt.Color(0, 51, 204));
        TiquetesActivosTitulo.setText("Tiquetes Activos");
        TiquetesActivosTitulo.setBorder(null);

        IDEmpleado.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        IDEmpleado.setText("ID Empleado");

        TextFieldNumEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldNumEmpleadoActionPerformed(evt);
            }
        });

        Nombre.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        Nombre.setText("Nombre");

        Descripcion.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        Descripcion.setText("Descripcion Problema");

        TextAreaDescripcion.setColumns(20);
        TextAreaDescripcion.setRows(5);
        jScrollPane1.setViewportView(TextAreaDescripcion);

        Telefono.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        Telefono.setText("Telefono");

        Email.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        Email.setText("E-mail");

        IDEmpleadoHistorial.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        IDEmpleadoHistorial.setText("ID Empleado");

        TiquetesActivos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jScrollPane2.setViewportView(TiquetesActivos);

        BotonCerrar.setText("Cerrar");
        BotonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(NuevoTiqueteTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TiquetesActivosTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IDEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextFieldNumEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(IDEmpleadoHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(TextFieldIDEmpleHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(37, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(BotonCrearTiquete, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(Version, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TituloPanelUSuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BotonMostrarTiquetes, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(BotonCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(107, 107, 107))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TituloPanelUSuario, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NuevoTiqueteTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TiquetesActivosTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addComponent(Version, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(IDEmpleado)
                                    .addComponent(TextFieldNumEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Nombre)
                                    .addComponent(TextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Telefono)
                                    .addComponent(TextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Email)
                                    .addComponent(TextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addComponent(Descripcion)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(IDEmpleadoHistorial)
                                    .addComponent(TextFieldIDEmpleHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BotonCrearTiquete)
                            .addComponent(BotonMostrarTiquetes))
                        .addGap(18, 18, 18)
                        .addComponent(BotonCerrar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonCrearTiqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCrearTiqueteActionPerformed

        try {
            Tiquete newTiquete = new Tiquete();

            newTiquete.setNombreEmpleado(TextFieldNombre.getText());
            newTiquete.setEmail(TextFieldEmail.getText());
            newTiquete.setDescripcionProblema(TextAreaDescripcion.getText());
            newTiquete.setIdEmpleado(Integer.parseInt(TextFieldNumEmpleado.getText()));
            newTiquete.setTelefono(Integer.parseInt(TextFieldTelefono.getText()));

            String aviso = "Se ha guardado satisfactoriamente";

            laCola.encola(new NodoColaTiquete(newTiquete));

            this.dispose();
            MenuUsuario menuUsuario = new MenuUsuario(laCola, tiquete);
            menuUsuario.setVisible(true);
            JOptionPane.showMessageDialog(null, aviso);
            
            System.out.println(laCola);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se ha podido crear el tiquete \nPor favor intente de nuevo, revisando cada uno de los datos");
        }
    }//GEN-LAST:event_BotonCrearTiqueteActionPerformed

    private void TextFieldNumEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldNumEmpleadoActionPerformed


    }//GEN-LAST:event_TextFieldNumEmpleadoActionPerformed

    private void limpiarcampos() {
        TextFieldNombre.setText(null);
        TextFieldNumEmpleado.setText(null);
        TextFieldTelefono.setText(null);
        TextFieldEmail.setText(null);
        TextAreaDescripcion.setText(null);
    }

    private void BotonMostrarTiquetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMostrarTiquetesActionPerformed
        try {
            int IDaBuscar = Integer.parseInt(TextFieldIDEmpleHistorial.getText());
            if (laCola.existe(IDaBuscar)) {
                TiquetesActivos.setText(laCola.buscar(IDaBuscar).toString());
            } else {
                JOptionPane.showMessageDialog(null, "Numero no registrado");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Digite un ID por favor");
        }
    }//GEN-LAST:event_BotonMostrarTiquetesActionPerformed

    private void BotonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCerrarActionPerformed
        this.dispose();
        FMenuPrincipal fmn = new FMenuPrincipal(laCola, tiquete);
        fmn.setVisible(true);
    }//GEN-LAST:event_BotonCerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCerrar;
    private javax.swing.JButton BotonCrearTiquete;
    private javax.swing.JButton BotonMostrarTiquetes;
    private javax.swing.JLabel Descripcion;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel IDEmpleado;
    private javax.swing.JLabel IDEmpleadoHistorial;
    private javax.swing.JLabel Nombre;
    private javax.swing.JTextField NuevoTiqueteTitulo;
    private javax.swing.JLabel Telefono;
    private javax.swing.JTextArea TextAreaDescripcion;
    private javax.swing.JTextField TextFieldEmail;
    private javax.swing.JTextField TextFieldIDEmpleHistorial;
    private javax.swing.JTextField TextFieldNombre;
    private javax.swing.JTextField TextFieldNumEmpleado;
    private javax.swing.JTextField TextFieldTelefono;
    private javax.swing.JTextPane TiquetesActivos;
    private javax.swing.JTextField TiquetesActivosTitulo;
    private javax.swing.JTextField TituloPanelUSuario;
    private javax.swing.JTextField Version;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
